export enum ActionsSuccessCodes {
  FIREBASE_USER_EXISTS = 'USER_EXISTS',
  FIREBASE_USER_NOT_EXISTS = 'USER_NOT_EXISTS',
  FIREBASE_SMS_SENT = 'SMS_SENT',
  FIREBASE_SMS_CONFIRMED = 'SMS_CONFIRMED',
  FIREBASE_VERIFICATION_CODE_CONFIRMED = 'FIREBASE_VERIFICATION_CODE_CONFIRMED',
}
