export enum AwsSnsErrorCode {
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  MESSAGE_SEND_FAILED = 'MESSAGE_SEND_FAILED',
  KMS_THROTTLING_EXCEPTION = 'KMS_THROTTLING_EXCEPTION',
  KMS_ACCESS_DENIED_EXCEPTION = 'KMS_ACCESS_DENIED_EXCEPTION',
  KMS_INVALID_STATE_EXCEPTION = 'KMS_INVALID_STATE_EXCEPTION',
  KMS_KEY_NOT_FOUND_EXCEPTION = 'KMS_KEY_NOT_FOUND_EXCEPTION',
  OPTED_OUT = 'OPTED_OUT',
  THROTTLING_EXCEPTION = 'THROTTLING_EXCEPTION',
  INVALID_PARAMETER = 'INVALID_PARAMETER',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
}
