export enum FirebaseErrorCode {
  FIREBASE_APPS_NOT_INITIALIZED = 'FIREBASE_APPS_NOT_INITIALIZED',
  VERIFICATION_CODE_NOT_FOUND = 'VERIFICATION_CODE_NOT_FOUND',
  VERIFICATION_CODE_INCORRECT = 'VERIFICATION_CODE_INCORRECT',
  MAX_VERIFICATION_CODES_REACHED = 'MAX_VERIFICATION_CODES_REACHED',
  VERIFICATION_CODE_EXPIRED = 'VERIFICATION_CODE_EXPIRED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
}
